// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {whatsapp} from '../models';

export function PickAttachments(arg1:string):Promise<Array<whatsapp.AttachmentDraft>>;

export function StageCapturedMedia(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<whatsapp.AttachmentDraft>;

export function StageDroppedAttachments(arg1:Array<string>):Promise<Array<whatsapp.AttachmentDraft>>;
