// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PickAttachments(arg1) {
  return window['go']['main']['App']['PickAttachments'](arg1);
}

export function StageCapturedMedia(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StageCapturedMedia'](arg1, arg2, arg3, arg4);
}

export function StageDroppedAttachments(arg1) {
  return window['go']['main']['App']['StageDroppedAttachments'](arg1);
}
